import Head from 'next/head'
import styles from '../styles/Home.module.css';

import Banner from  '../components/banner/banner';
import Navbar from  '../components/nav/navbar';
import SectionCards from  '../components/card/section-cards';

import { getVideos, getPopularVideos, getWatchItAgainVideos } from '../lib/videos';

import useRedirectuser from '../utils/redirectUser';


//Here you are using Server Side Rendering
export async function getServerSideProps(context) {

  const { userId,  token } = await useRedirectuser(context);

  if (!userId) {
    return {
    props: {},
    redirect: {
        destination: '/login',
        permanent: false,
    },
    }
}


  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);
  // console.log({ watchItAgainVideos });

  let disneyVideos = await getVideos("disney trailer");
  disneyVideos = JSON.parse(JSON.stringify(disneyVideos));

  let productivityVideos = await getVideos("Productivity");
  productivityVideos = JSON.parse(JSON.stringify(productivityVideos));

  let travelVideos = await getVideos("travel");
  travelVideos = JSON.parse(JSON.stringify(travelVideos));

  let popularVideos = await getPopularVideos();
  popularVideos = JSON.parse(JSON.stringify(popularVideos));

  return { props: { disneyVideos, productivityVideos, travelVideos, popularVideos, watchItAgainVideos } };
}

export default function Home({disneyVideos, productivityVideos, travelVideos, popularVideos, watchItAgainVideos}) {

  // startFetchMyQuery();
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar/>

        <Banner
          videoId="4zH5iYM4wJo"
          title="Clifford the Red Dog"
          subTitle="A very cute dog"
          imgUrl="/static/clifford.png"
          />

        <div className={styles.sectionWrapper}>
          <SectionCards
            title="Disney" 
            videos={disneyVideos}
            size="large"
          />
          
          <SectionCards
            title="Watch it again" 
            videos={watchItAgainVideos}
            size="small"
          />

          <SectionCards
            title="Travel" 
            videos={travelVideos}
            size="small"
          />
          <SectionCards
            title="Productivity" 
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards
            title="Popular" 
            videos={popularVideos}
            size="small"
          />
        </div>
      </div>
      
      

    </div>
  )
}
